### ISSUE TITLE
get-pip.py for Python 3.5

### ISSUE THREAD

**Issue by JustAnotherArchivist** [pypa/get-pip#83]
Since yesterday's release of pip 21.0, get-pip.py no longer supports Python 3.5 due to using f-strings:

```
Traceback (most recent call last):
  File "get-pip.py", line 24226, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/tmp/tmppehzzo9e/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

Could a /3.5/get-pip.py be added, analogous to the 3.4 and older versions?

**Comment by greenmang0** [comment]
Yes, facing the same issue. 

```
test-node01:~$ curl https://bootstrap.pypa.io/get-pip.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1883k  100 1883k    0     0  13.1M      0 --:--:-- --:--:-- --:--:-- 13.1M
Traceback (most recent call last):
  File "<stdin>", line 24226, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpLEYzBo/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by pramodk** [comment]
Same issue here!

**Comment by Cappuccinuo** [comment]
Same issue here for python3.5

```bash
+ python3 /tmp/get-pip.py
Traceback (most recent call last):
  File "/tmp/get-pip.py", line 24226, in <module>
    main()
  File "/tmp/get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "/tmp/get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/tmp/tmps00d7qag/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

$ python3 --version
Python 3.5.3
```

Also for python2

```bash
$ python --version
Python 2.7.13
$ python /tmp/get-pip.py
Traceback (most recent call last):
  File "/tmp/get-pip.py", line 24226, in <module>
    main()
  File "/tmp/get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "/tmp/get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpeSPv0D/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by pradyunsg** [comment]
Ah, I'll add that in.

**Comment by pradyunsg** [comment]
Filed #84 and python/psf-salt#199, which (when merged) should fix this. :)

**Comment by anetanel** [comment]
How long before this change is reflected in the download url 'https://bootstrap.pypa.io/get-pip.py'?
As of now, I still see the old file (23-Jan-2021 15:00), and our CI is broken because of it.

**Comment by okeren-cx** [comment]
@anetanel The site will update when [this](https://github.com/python/psf-salt/pull/199) PR by @pradyunsg will be merged
In the meantime you can use 3.4 instead and see if that works, just point your CI to `https://bootstrap.pypa.io/3.4/get-pip.py`

**Comment by JustAnotherArchivist** [comment]
https://bootstrap.pypa.io/3.5/get-pip.py is now available. Thanks, everyone!

**Comment by kristoforerickson** [comment]
@JustAnotherArchivist https://bootstrap.pypa.io/get-pip.py has not been updated so my CircleCI build is still failing.

**Comment by webknjaz** [comment]
@kristoforerickson you should be using a different URL.

**Comment by kristoforerickson** [comment]
@webknjaz it's not me but CircleCI -- I guess I'll ask them to change the URL...

**Comment by danielfm** [comment]
Just tried https://bootstrap.pypa.io/3.5/get-pip.py, but I'm getting HTTP 404.

Is this expected?

**Comment by JustAnotherArchivist** [comment]
@danielfm Everything got moved around due to #61. The URL is now <https://bootstrap.pypa.io/pip/3.5/get-pip.py>.

**Comment by Souleymanebyte** [comment]
I'm trying to install montage packages on ubuntu last version but it's failing

**Comment by asankabet2** [comment]
i need a fix. i googled mt issue and this was given. anyone here to help?

**Comment by webknjaz** [comment]
@asankabet2 this is a legacy mechanism, don't use it. Ask your vendor where to get pip for your specific runtime. Though, nowadays, it's just there.
